;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Door.Break",DevComment="")
+GameplayTagList=(Tag="Ability.Door.Open",DevComment="")
+GameplayTagList=(Tag="Ability.Door.Open.Trigger",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.Attribute.Damage",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.Attribute.FireRate",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.Attribute.Penetration",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.Cost",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.Cost.Fire",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.Cost.Reload",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.Operation.BreakDoor",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.Operation.BreakDoor.Trigger",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.Operation.Fire",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.Operation.Reload",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.Slot",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.State.OnShoot",DevComment="")
+GameplayTagList=(Tag="Ability.Weapon.State.ShotCount",DevComment="")
+GameplayTagList=(Tag="Montage.Magazine.Dropped",DevComment="")
+GameplayTagList=(Tag="Montage.Magazine.Inserted",DevComment="")
+GameplayTagList=(Tag="Montage.Magazine.Picked",DevComment="")
+GameplayTagList=(Tag="Montage.Magazine.Released",DevComment="")
+GameplayTagList=(Tag="Montage.Rack",DevComment="")
+GameplayTagList=(Tag="Montage.Rack.Ended",DevComment="")
+GameplayTagList=(Tag="Montage.Rack.Started",DevComment="")

